### ISSUE TITLE
english

### ISSUE THREAD

**Issue by AlessioSavelli** [SeppHansen/SLSS-CANAnalyser#2]
Hey men i love your work, is really usefull!!!!!
Nice Job.

if I can I would like to give you an advice, i suggest you to make a database or json file etc. with the text to be inserted into the GUI.
Put the file in a folder called 'languages', so that anyone can translate it .

I'm waiting for English version.

good luck.

**Comment by SeppHansen** [comment]
Hi Alessio,

First, sorry for my late reply. In my actual busy situation I just forgot to answer you. Sorry for that pal...
Second, thank' s for the advice. I started that project for myself, to simplify the CAN signal analysis and increase CAN knowledge for other projects. At this time I hadn't thought, that so many (non-german) people could also realy need such a software, so i designed etherything in german. Your idea is very good and it shouldn't be a big problem to implement it in the next version of my software. 
I hope my busy situation will become better the next weeks, so you need to stay patient a little bit longer...

kind regards
Sebastian

**Comment by SeppHansen** [comment]
It finally comes to an end. With the actual version 1.1.0.14 you will have to possibility to change the language via German and English (via the menu or bey clicking on the flag symbol inside the header of the main window). The selected language setting will be stored so that it starts in yoour prefered language at the next software start!

Many thanks to my pal Ron Zlotnik who helps me as a native speaker to translate the menu elements and messages to a hopefully good English appearance!
